### ISSUE TITLE
Licensing of mopidy-async-client

### ISSUE THREAD

**Issue by djmattyg007** [SvineruS/SvineruS#2]
Hello. I was hoping to package mopidy-async-client for Arch Linux (in the AUR). I'm writing this here because the repo in question does not have issues enabled.

https://github.com/SvineruS/mopidy-async-client

During the packaging process I realised I was unable to find a relevant software license in the codebase.

I understand your software is a fork of mopidy-json-client. That project is licensed under Apache, and under normal circumstances I would just assume that, as a derivative work, your project would default to the Apache license.

However, it looks like you did genuinely rewrite all of the original code in your initial commit after the fork:

https://github.com/SvineruS/mopidy-async-client/commit/cf00d1ed6d9a07289b8a566086733ecf7bdda6f2

Therefore, it isn't clear what the license of your code is. Would you be able to clarify? The ideal situation would be the creation of a `LICENSE` file in the actual repository.

**Comment by SvineruS** [comment]
@djmattyg007 hi. sorry about issues, I don't know why they were turned off :) the conversation can be continued there, if convenient. 
package in AUR is cool! only I don't understand licenses at all, will it be ok if I choose GNU?

**Comment by djmattyg007** [comment]
If by GNU you mean the GNU GPL, then yes, I don't think there's anything wrong with that.

Regardless of which license you choose, I recommend doing the following things:

- Adding a copy of the license text to your repo in a license file
- Ensuring that license file is included in the packages you publish to PyPI
- Adding a note to the readme indicating what the license is
- Adding the relevant configuration to the `pyproject.toml` file to indicate the license. It will probably look something like this: https://github.com/djmattyg007/mopidy-advanced-scrobbler/blob/master/setup.cfg#L7

**Comment by SvineruS** [comment]
@djmattyg007 hi. sorry for the delay, I added a license.

**Comment by djmattyg007** [comment]
No need to be sorry :) Thank you so much for being so responsive!
